#!/usr/bin/env bash

fg_black="$(tput setaf 0)"
fg_red="$(tput setaf 1)"
fg_green="$(tput setaf 2)"
fg_yellow="$(tput setaf 3)"
fg_blue="$(tput setaf 4)"
fg_magenta="$(tput setaf 5)"
fg_cyan="$(tput setaf 6)"
fg_white="$(tput setaf 7)"

info() {
    echo ""
    echo "${fg_green}> $@"
}

info "Include global \`~/.yadm-gitconfig\` in yadm's gitconfig"
yadm gitconfig include.path '~/.yadm-gitconfig'
