FZF_DEFAULT_COMMAND=fd
#FZF_DEFAULT_OPTS='--border'
export FZF_DEFAULT_COMMAND FZF_DEFAULT_OPTS

FZF_CTRL_R_OPTS='--border'
export FZF_CTRL_R_OPTS

FZF_CTRL_T_COMMAND=fd
FZF_CTRL_T_OPTS='--border'
export FZF_CTRL_T_COMMAND FZF_CTRL_T_OPTS

FZF_ALT_C_COMMAND='fd -t d'
FZF_ALT_C_OPTS='--border'
export FZF_ALT_C_COMMAND FZF_ALT_C_OPTS

