# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]

prepend_keymap = [
    # Smart Enter
    { on = "<Enter>", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
]

append_keymap = [
    # Drag-and-Drop
    { on = "R", run = ''' shell 'ripdrag "$@" -x 2>/dev/null &' --confirm ''', desc = "Open RipDrag with the selected items to allow Drag-and-Drop" },

    # Create directory
    { on = "A", run = "create --dir", desc = "Create directory" },

    # Bashmount
    { on = "M", run = "plugin bashmount", desc = "Run bashmount" },
]
