[open]

prepend_rules = [
    { mime = "text/csv", use = [ "open", "edit", "reveal" ] },
]


[opener]

play = [
    { run = 'handlr open "$@"', desc = 'Open (handlr)' },
    { run = 'mpv "$@"', desc = 'mpv' },
]

open = [
    { run = 'handlr open "$@"', desc = 'Open (handlr)' },
]

