[manager]

show_hidden = true


[open]

prepend_rules = [
    { mime = "image/*", use = [ "open", "reveal", "exif" ] },
    { mime = "text/csv", use = [ "open", "edit", "reveal" ] },
]


[opener]

play = [
    { run = 'handlr open "$@"', desc = 'Open (handlr)' },
    { run = 'mpv "$@"', desc = 'mpv' },
]

reveal = [
    { run = 'reveal "$1"', desc = "Reveal", for = "linux" },
]

exif = [
    { run = ''' exiftool "$1"; echo "Press enter to exit"; read _ ''', block = true, desc = "Show EXIF", for = "unix" },
]

open = [
    { run = 'handlr open "$@"', desc = 'Open (handlr)' },
]

