#!/bin/sh

SCRIPT="$(realpath "$0")"
SCRIPT_DIR="$(dirname "$SCRIPT")"

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"
CONFIG_DIR="${XDG_CONFIG_HOME}/bspwm"
RUN_DIR="${CONFIG_DIR}/run"
mkdir -p "$RUND_DIR"

PATH="${HOME}/.local/bin:${PATH}"
export PATH

# --- Autostart ---

# sxhkd
#sxhkd_pidfile="${RUN_DIR}/sxhkd.pid"
#[[ -f $sxhkd_pidfile ]] && kill "$(< "$sxhkd_pidfile")" 2>/dev/null
#sxhkd -c "${XDG_CONFIG_HOME}/sxhkd/bspwm.sxhkdrc" & echo "$!" >"$sxhkd_pidfile"

#pgrep -x sxhkd >/dev/null || sxhkd &
pkill sxhkd; sxhkd & # sxhkd is started by nix package of bspwm but with wrong PATH
pkill picom; picom --experimental-backends & # Experimental for blur with "dual_kawase"
feh --bg-fill ~/Pictures/\[Wallpapers\]/1920x1080/tree-on-a-hill.jpg &


# --- Setup ---

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Config
bspc config window_gap              20
bspc config border_width            1
bspc config pointer_follows_monitor false
bspc config focus_follows_pointer   true
bspc config focused_border_color    "#0071db"
bspc config removal_adjustment      "false"
