---
name: Close Stale Issues
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "30 1 * * *"  # Daily
jobs:
  Stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          close-issue-message: >-
            This issue was closed because it has been labeled as stale for 7
            days with no activity.
          days-before-close: 7
          days-before-stale: 60
          exempt-all-assignees: true
          exempt-issue-labels: in develop, 1, 2, 3
          exempt-pr-labels: in develop, 1, 2, 3
          stale-issue-label: stale
          stale-issue-message: >-
            This issue has been labeled as stale because it has been open 60
            days with no activity. Remove stale label or comment or this will
            be closed in 7 days.
          stale-pr-label: stale
