#!/usr/bin/env bash

set -euo pipefail

function start() {
  nohup "$@" >/dev/null 2>&1 & disown;
}

pkill -x 'easyeffects' \
  || pkill -x '.easyeffects-wr'

start easyeffects --gapplication-service

