#!/usr/bin/env python3

import select
import keyboard
import sys
import os
from time import time
from os import path

__SCRIPT__ = sys.argv[0]
__SCRIPT_DIR__ = path.dirname(__SCRIPT__)

__FIFO__ = __SCRIPT_DIR__ + "/.fifo"

def main():
    if path.exists(__FIFO__):
        os.remove(__FIFO__)
    os.mkfifo(__FIFO__)

    key_times = {}
    key_counts = {}

    while True:
        with open(__FIFO__, 'r') as fifo:
            for key in fifo:
                ## Block until data is available
                #select.select([fifo],[],[fifo])

                #key = fifo.read().rstrip('\n').lower()
                key = key.rstrip()
                timestamp = time_millis()

                if key not in key_times:
                    key_times[key] = timestamp
                    key_counts[key] = 0
                    continue

                first_time = key_times[key]
                delta = timestamp - first_time

                if delta > 700:
                    key_times[key] = timestamp
                    key_counts[key] = 0
                    continue

                key_counts[key] += 1

                if key_counts[key] < 5:
                    continue

                print(f"SEND KEY: {key}")

                keyboard.press_and_release(key)
                key_times[key] = timestamp
                key_counts[key] = 0


def time_millis():
    return round(time() * 1000)


if __name__ == '__main__':
    main()