#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'
enable_cursor_positioning = false


[var]
  # When copying this config to an ssh target, the username is only shown if
  # it does not match the MainUser name.
  MainUser = "^x3ro$"


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = "battery"
    style = "diamond"
    trailing_diamond = ' '
    foreground = "p:_surface0"
    background = "p:red"
    template = "{{ if le .Percentage 20 }} <b>{{ .Icon }}{{ .Percentage }} </b>{{ end }}"

    [blocks.segments.properties]
      discharging_icon = "󰁺 "
      charging_icon = "󰢜 "
      charged_icon = "󰁹 "
      display_error = true

  [[blocks.segments]]
    type = "os"
    style = "diamond"
    foreground = 'p:fg_host'
    background = 'p:bg_host'
    leading_diamond = ''
    trailing_diamond = ''
    template = "{{.Icon}} "

  [[blocks.segments]]
    type = 'session'
    # style = 'powerline'
    style = 'diamond'
    foreground = 'p:fg_host'
    background = 'p:bg_host'
    powerline_symbol = ''
    # leading_diamond = ''
    trailing_diamond = ''
    templates = [
      '{{ if .SSHSession }} {{ end }}',
      '{{ if not (matchP .Var.MainUser .UserName) }}{{ .UserName }}{{ end }}',
      '{{ if .SSHSession }}@{{ .HostName }}{{ end }} '
    ]


[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'path'
    style = 'diamond'
    leading_diamond = ''
    foreground = 'p:fg_path'
    background = 'p:bg_path'
    template = '<b>  {{ path .Path .Location }} </b>'

    [blocks.segments.properties]
      style = 'powerlevel'
      max_width = 21

  [[blocks.segments]]
    type = 'git'
    style = 'accordion'
    powerline_symbol = ''
    foreground = 'p:fg_git'
    # foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:surface0{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}', '{{ if gt .Ahead 0 }}p:white{{ end }}']
    background = 'p:bg_git'
    # background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}', '{{ if gt .Ahead 0 }}#49416D{{ end }}', '{{ if gt .Behind 0 }}#7A306C{{ end }}']
    # template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '

    [blocks.segments.properties]
      branch_max_length = 25
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = "text"
    style = "accordion"
    powerline_symbol = ''
    background = "p:_yellow"
    template = ""

  [[blocks.segments]]
    type = "text"
    style = "accordion"
    powerline_symbol = ''
    background = "p:_peach"
    template = ""

  [[blocks.segments]]
    type = "text"
    style = "accordion"
    powerline_symbol = ''
    background = "p:_red"
    template = ""


[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = "time"
    style = "diamond"
    leading_diamond = ''
    trailing_diamond = ''
    foreground = "p:fg_time"
    background = "p:bg_time"
    template = "  {{ .CurrentDate | date .Format }} "

    [properties]
      time_format = "15:04:05"

  [[blocks.segments]]
    type = "executiontime"
    style = "diamond"
    trailing_diamond = ''
    foreground = "p:white"
    background = "p:_surface0"
    template = "  {{ .FormattedMs }} "

    [blocks.segments.properties]
      threshold = 500
      style = "austin"


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground = 'p:green'
    foreground_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']
    template = ' {{ .Code }}'

    [blocks.segments.properties]
      always_enabled = false

  [[blocks.segments]]
    alias = 'Prompt'
    type = 'text'
    style = 'plain'
    foreground = 'p:green'
    foreground_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']
    template = ' ❯'


[secondary_prompt]
  foreground = 'p:green'
  foreground_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']
  template = '•❯ '


[palette]
  # --- Catppuccin Mocha ---
  _rosewater = "#f5e0dc"
  _flamingo  = "#f2cdcd"
  _pink      = "#f5c2e7"
  _mauve     = "#cba6f7"
  _red       = "#f38ba8"
  _maroon    = "#eba0ac"
  _peach     = "#fab387"
  _yellow    = "#f9e2af"
  _green     = "#a6e3a1"
  _teal      = "#94e2d5"
  _sky       = "#89dceb"
  _sapphire  = "#74c7ec"
  _blue      = "#89b4fa"
  _lavender  = "#b4befe"
  _text      = "#cdd6f4"
  _subtext1  = "#bac2de"
  _subtext0  = "#a6adc8"
  _overlay2  = "#9399b2"
  _overlay1  = "#7f849c"
  _overlay0  = "#6c7086"
  _surface2  = "#585b70"
  _surface1  = "#45475a"
  _surface0  = "#313244"
  _base      = "#1e1e2e"
  _mantle    = "#181825"
  _crust     = "#11111b"

  # --- Regular colors ---
  white = 'p:_text'
  red   = 'p:_red'
  green = 'p:_green'

  # --- Segment colors ---
  fg_host = 'p:_text'
  bg_host = 'p:_surface0'

  fg_path = 'p:_surface0'
  bg_path = 'p:_sapphire'

  fg_git  = 'p:_surface0'
  bg_git  = 'p:_green'

  fg_env  = 'p:_surface0'
  bg_env  = 'p:_peach'

  fg_time = 'p:_surface0'
  bg_time = 'p:_mauve'
